adopted-ember-addons/active-model-adapter

active-model-adapter-source.gemspec
active-model-adapter depends on Ember Data.
=> Depend on `ember-data-source` instead of `ember-source`

active-model-adapter-source.gemspec
The following files are required but not bundled now.
```
lib/ember/data/active_model/adapter/
├── source.rb
└── version.rb
```
=> Add missing `.rb` files to be bundled to active-model-adapter gem

addon/active-model-serializer.js, tests/integration/active-model-serializer-test.js
Given { some_belongs_to_id: 42, some_belongs_to_type: 'some_type' },
transforms it be conform to what the json-serializer expects, ie
{ some_belongs_to_id: { id:42, type: 'some_type'}
Fixes #18
cc/ @wecc @igorT @lessless
=> Support for weird polymorphic relationship format

addon/active-model-serializer.js, bower.json, tests/integration/active-model-adapter-test.js, tests/integration/active-model-serializer-test.js
Previously, the following did not load relationships correctly when using the new Serializer API:
```javascript
{
evil_minion: {
id: 1,
relationship_name: {
id: 1,
type: 'super-minion'
}
}
}
// push payload
store.findRecord('evil-minion', '1').then((m) => m.get('relationship.id'));
// resolves to null
```
The object format is what the AMS gem expects by default, so we return
if we find that. Otherwise, we use the "weird format" introduced by
https://github.com/ember-data/active-model-adapter/pull/20.
Fixes #15.
=> Polymorphic fixes

app/instance-initializers/active-model-adapter.js
in order to align it with https://github.com/ember-data/active-model-adapter/blob/master/app/initializers/active-model-adapter.js#L8.
Or is it better to just include it in ActiveModelSerializer?
cc @fivetanley
=> Set isNewSerializerAPI for ActiveModelSerializer

addon/active-model-serializer.js, bower.json, package.json, tests/integration/active-model-adapter-test.js, tests/integration/active-model-serializer-test.js, tests/integration/old-serializer-api-test.js
This fixes an issue where missing polymorphic keys in a payload would
trigger an assertion.
For example, if a Book model had a `hasMany` relationship to the Author
model, but the `authors` key was missing in the payload for a
polymorphic relationship, an assertion was incorrectly triggered.
This worked before 1.13, and this commit restores that functionality.
Fixes emberjs/data#3630
We also fixed the tests around error pointers that got updated when ember data installed to a newer version via bower. The JSONAPI spec says that error pointers must have a slash at the beginning of them.
cc @wecc
=> [bugfix RELEASE] Restore polymorphic support

addon/active-model-serializer.js
This makes the code return early in the `if (relationship.options.polymorphic) {` block (just like in the else part).
=> Improve code readability

app/initializers/active-model-adapter.js
Only application instance is passed to `initialize` method after `ember 2.1.0-beta`, this fixes the deprecation warning in a backwards compatible way.
```
DEPRECATION: The `initialize` method for Application initializer 'container-debug-adapter' should take only one argument - `App`, an instance of an `Application`. [deprecation id: ember-application.app-initializer-initialize-arguments]
```
=> Fix initializer deprecation warning for >= ember 2.1.0

app/instance-initializers/active-model-adapter.js
Container is not used in the instance initializer so there is no point in setting it. Also fixes  #40.
=> Remove unused container in instance initializer, fixes #40

babel-options.js
Fixes:
```
[BABEL] The transformer es6.parameters.rest has been renamed to es6.parameters
[BABEL] The transformer es6.parameters.default has been renamed to es6.parameters
```
=> Fix babel rename option warning

app/instance-initializers/active-model-adapter.js
Ember 2.1 deprecates application.registry as it contains private
methods. This commit replaces uses of the private registry API
with the public equivalents.
=> Do not use application.registry

bower.json
Ember Data 2.1 was released. :tada: 
http://emberjs.com/blog/2015/10/05/ember-data-2-1-released.html
Should active-model-adapter be also updated to 2.1?
=> Test against Ember Data 2.1

app/instance-initializers/active-model-adapter.js
https://github.com/ember-data/active-model-adapter/commit/c2564d45a27da7e3525693d1f37af07373538213 broke the addon, since the register function wasn't binded to the right context.
=> Bind instance initializer register function to the right context

README.md, addon/active-model-serializer.js, app/initializers/active-model-adapter.js, bower.json, package.json, tests/integration/active-model-serializer-test.js
This means that the following would be supported:
```javascript
{
"post": {
// belongsTo, would normally be author_id
"author": 1,
// hasMany, would normally be pancake_hero_ids
"pancake_heros": [1,2,3]
}
}
```
Should close https://github.com/ember-data/active-model-adapter/issues/54
=> [bugfix] support relationship names without _id suffix

addon/active-model-adapter.js, tests/integration/active-model-adapter-test.js
Fix's a regression in ember-data >= 2.4.0 related to arguments changing in RESTAdapter's handleResponse function https://github.com/emberjs/data/pull/3930, pass along requestData as argument in active-model-adapter handleResponse override method as well as fix handleResponse - returns ajax response if not 422 response test
closes https://github.com/ember-data/active-model-adapter/issues/82
=> Fix's a regression in ember-data >= 2.4.0 related to handleResponse changes

package.json, yarn.lock
`ember-try` is already included by default in Ember CLI
=> Remove explicit `ember-try` dependency

.travis.yml, config/ember-try.js
This adds `ember-try` scenarios for Ember 2.0, 2.4, 2.8, 2.12 and 2.16. It also enables the scenarios so that they run on CI. Ember 2.12 and above are currently failing due to a broken container access so I added them to `allow_failures` for now.
=> Add more ember-try scenarios

addon/active-model-adapter.js, addon/active-model-serializer.js, package.json, yarn.lock
=> Fix ember-inflector deprecations

package.json
This is required for many of the current releases of used addons in here and Ember, Ember Data and Ember CLI themselves.
This should be considered as a breaking change which requires us to bump the major version once released.
=> [BREAKING] Increase minimum Node.js version to v4.5

.travis.yml, package.json
CI fails because latest yarn is installed and run there. yarn is now incompatible with Node 4.
This PR proposes to drop support for NodeJs versions < 10, 11 and 13.
It would unblock
- https://github.com/ember-data/active-model-adapter/pull/130
- Dependabot upgrades.
=> NodeJs: Update support policy

addon/active-model-serializer.ts
The purpose of this MR is to use `dasherize` instead of `normalizeModelName` in the `active-model-serializer` as it has been deprecated by ember-data `v4.7.3`
Following the deprecation message, it recommends to use `dasherize` from `@ember/string` instead of `normalizeModelName`
```
Deprecation message: Error: the helper function normalizeModelName is deprecated. You should use model names that are already normalized, or use string helpers of your own. This function is primarily an alias for dasherize from @ember/string.
```
=> Use dasherize instead of normalizeModelName
